"""Initial migration with all current fields

Revision ID: 7374c8a1b602
Revises: 
Create Date: 2025-09-15 02:28:20.766248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7374c8a1b602'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.alter_column('devices', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('devices', 'first_seen',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_devices_device_type'), table_name='devices')
    op.drop_index(op.f('ix_devices_mac_address'), table_name='devices')
    op.create_index(op.f('ix_devices_mac_address'), 'devices', ['mac_address'], unique=False)
    op.create_index(op.f('ix_devices_motherboard_serial'), 'devices', ['motherboard_serial'], unique=False)
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_index(op.f('ix_devices_system_uuid'), 'devices', ['system_uuid'], unique=True)
    op.alter_column('hardware_details', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hardware_details', 'wmi_raw_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('hardware_details', 'lshw_raw_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('hardware_details', 'collection_timestamp',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(None, 'hardware_details', type_='foreignkey')
    op.create_foreign_key(None, 'hardware_details', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.drop_column('hardware_details', 'network_mac')
    op.drop_column('hardware_details', 'disk_serial')
    op.drop_column('hardware_details', 'capacity_bytes')
    op.drop_column('hardware_details', 'slot_location')
    op.drop_column('hardware_details', 'ram_serial')
    op.drop_column('hardware_details', 'gpu_uuid')
    op.drop_column('hardware_details', 'cpu_serial')
    op.drop_column('hardware_details', 'firmware_version')
    op.drop_column('hardware_details', 'usb_serial')
    op.drop_column('hardware_details', 'psu_serial')
    op.drop_column('hardware_details', 'speed')
    op.drop_column('hardware_details', 'part_number')
    op.alter_column('history_logs', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('history_logs', 'change_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_history_logs_timestamp'), 'history_logs', ['timestamp'], unique=False)
    op.drop_constraint(None, 'history_logs', type_='foreignkey')
    op.create_foreign_key(None, 'history_logs', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history_logs', type_='foreignkey')
    op.create_foreign_key(None, 'history_logs', 'devices', ['device_id'], ['id'])
    op.drop_index(op.f('ix_history_logs_timestamp'), table_name='history_logs')
    op.alter_column('history_logs', 'change_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('history_logs', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('hardware_details', sa.Column('part_number', sa.VARCHAR(length=255), nullable=True))
    op.add_column('hardware_details', sa.Column('speed', sa.VARCHAR(length=100), nullable=True))
    op.add_column('hardware_details', sa.Column('psu_serial', sa.VARCHAR(length=255), nullable=True))
    op.add_column('hardware_details', sa.Column('usb_serial', sa.VARCHAR(length=255), nullable=True))
    op.add_column('hardware_details', sa.Column('firmware_version', sa.VARCHAR(length=100), nullable=True))
    op.add_column('hardware_details', sa.Column('cpu_serial', sa.VARCHAR(length=255), nullable=True))
    op.add_column('hardware_details', sa.Column('gpu_uuid', sa.VARCHAR(length=255), nullable=True))
    op.add_column('hardware_details', sa.Column('ram_serial', sa.VARCHAR(length=255), nullable=True))
    op.add_column('hardware_details', sa.Column('slot_location', sa.VARCHAR(length=100), nullable=True))
    op.add_column('hardware_details', sa.Column('capacity_bytes', sa.BIGINT(), nullable=True))
    op.add_column('hardware_details', sa.Column('disk_serial', sa.VARCHAR(length=255), nullable=True))
    op.add_column('hardware_details', sa.Column('network_mac', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'hardware_details', type_='foreignkey')
    op.create_foreign_key(None, 'hardware_details', 'devices', ['device_id'], ['id'])
    op.alter_column('hardware_details', 'collection_timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('hardware_details', 'lshw_raw_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('hardware_details', 'wmi_raw_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('hardware_details', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_devices_system_uuid'), table_name='devices')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_motherboard_serial'), table_name='devices')
    op.drop_index(op.f('ix_devices_mac_address'), table_name='devices')
    op.create_index(op.f('ix_devices_mac_address'), 'devices', ['mac_address'], unique=1)
    op.create_index(op.f('ix_devices_device_type'), 'devices', ['device_type'], unique=False)
    op.alter_column('devices', 'first_seen',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('devices', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('devices', 'updated_at')
    # ### end Alembic commands ###
