"""add_alert_thresholds_table

Revision ID: add_alert_thresholds
Revises: 7374c8a1b602
Create Date: 2025-09-19 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_alert_thresholds'
down_revision = '7374c8a1b602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), sa.ForeignKey('devices.id'), nullable=True),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('comparison', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_thresholds_id'), 'alert_thresholds', ['id'], unique=False)
    op.create_index('idx_alert_thresholds_metric', 'alert_thresholds', ['metric_type'], unique=False)
    op.create_index('idx_alert_thresholds_device', 'alert_thresholds', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alert_thresholds_device', table_name='alert_thresholds')
    op.drop_index('idx_alert_thresholds_metric', table_name='alert_thresholds')
    op.drop_index(op.f('ix_alert_thresholds_id'), table_name='alert_thresholds')
    op.drop_table('alert_thresholds')
    # ### end Alembic commands ###
